use customer_shopping;
SELECT * FROM customer_shopping_behaviour_clean_data;

-- QUESTIONS
-- 1. What is the total revenue generated by Male vs Female customers?
SELECT sum(purchase_amount) as total_revenue,
gender
FROM customer_shopping_behaviour_clean_data
group by gender

-- 2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, 
purchase_amount
FROM customer_shopping_behaviour_clean_data
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_shopping_behaviour_clean_data)

-- 3. Which are the top 5 products with the highest average rating?
SELECT item_purchased,
round(AVG(review_rating), 2) AS average_product_rating
FROM customer_shopping_behaviour_clean_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5

-- 4. Compare the average purchaed amounts between Standard and Express Shipping. NOTE: Shipping Type column is not on the data set. I also attempted this for learning sake.
SELECT shipping_type,
ROUND(AVG(purchase_amount), 2)
FROM customer_shopping_behaviour_clean_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) as total_customers, 
ROUND(AVG(purchase_amount), 2) AS average_spend,
SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behaviour_clean_data
GROUP BY subscription_status
ORDER BY total_revenue, average_spend DESC

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
 ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 0) AS discount_rate
FROM customer_shopping_behaviour_clean_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5

-- 7. Segment customers into Now, Returning and Loyal based on their total numbers of previous purchases and show the count of each segment.
WITH customer_tyPeCTE AS (
SELECT customer_id,
previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer_shopping_behaviour_clean_data 
)
SELECT customer_segment,
COUNT(*) AS 'Number of customers'
FROM customer_tyPeCTE
GROUP BY customer_segment

-- 8. What are the top 3 most purchased products within each category?
WITH item_countCTE AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_order,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_shopping_behaviour_clean_data
GROUP BY categorY, item_purchased
)
SELECT item_rank,
category,
item_purchased,
total_order
FROM item_countCTE
WHERE item_rank <= 3

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subsxribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer_shopping_behaviour_clean_data
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC

-- 10. What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS revenue_contribution
FROM customer_shopping_behaviour_clean_data
GROUP BY age_group 
ORDER BY revenue_contribution DESC

